export const SET_CONFIG = "SET_CONFIG";

export const SET_DIRLIST = "SET_DIRLIST";
export const SET_CURRENT_DIR = "SET_CURRENT_DIR";
export const SET_DIRLIST_LOADING = "SET_DIRLIST_LOADING";

export const SET_FILESLIST = "SET_FILESLIST";
export const SET_FILESLIST_LOADING = "SET_FILESLIST_LOADING";
export const RESET_FILELIST_SELECTED = "RESET_FILELIST_SELECTED";
export const ADD_FILESLIST_SELECTED = "SET_FILESLIST_SELECTED";
export const SET_FILESLIST_SELECT = "SET_FILESLIST_SELECT";
export const REMOVE_FILESLIST_SELECTED = 'REMOVE_FILESLIST_SELECTED';
export const SET_FILESLIST_LASTSELECTED = 'SET_FILESLIST_LASTSELECTED';
