export const SET_CONFIG = "SET_CONFIG";

export const SET_VIEW = "SET_VIEW";

export const SET_DIRLIST = "SET_DIRLIST";
export const SET_CURRENT_DIR = "SET_CURRENT_DIR";
export const SET_DIRLIST_LOADING = "SET_DIRLIST_LOADING";

export const SET_FILESLIST = "SET_FILESLIST";
export const SET_FILESLIST_LOADING = "SET_FILESLIST_LOADING";
export const ADD_FILE_FILELIST = "ADD_FILE_FILELIST";
export const REMOVE_FILE_FILELIST = "REMOVE_FILE_FILELIST";
export const RENAME_FILE_FILELIST = "RENAME_FILE_FILELIST";

export const SET_FILESLIST_SELECTED = "SET_FILESLIST_SELECTED";
export const SET_FILESLIST_SELECT = "SET_FILESLIST_SELECT";
export const REMOVE_FILESLIST_SELECTED = "REMOVE_FILESLIST_SELECTED";
export const SET_FILESLIST_LASTSELECTED = "SET_FILESLIST_LASTSELECTED";

export const SET_CLIPBOARD = "SET_CLIPBOARD";
export const SET_CLIPBOARD_CUT = "SET_CLIPBOARD_CUT";

export const SET_SEARCH = "SET_SEARCH";
export const SET_SORT_ORDER = "SET_SORT_ORDER";

export const ADD_JOB = "ADD_JOB";
export const SET_STATUS_JOB = "SET_STATUS_JOB";
export const INCREMENT_JOB_PROGRESS = "INCREMENT_JOB_PROGRESS";
export const SET_UPLOAD_PROGRESS = "SET_UPLOAD_PROGRESS";
